name: Deploy Node.js App to Hostinger


on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
   
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install dependencies
        run: npm install
        working-directory: WebApp/Backend/

      - name: Set up environment variables
        run: |
          echo "PORT=5000" >> $GITHUB_ENV
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          protocol: ftp
          server: ${{ secrets.FTP_HOST }} 
          username: ${{ secrets.FTP_USERNAME }}  
          password: ${{ secrets.FTP_PASSWORD }}  
          port: ${{ secrets.FTP_PORT }}  
          local-dir: ./WebApp/Backend/   # Path to the local directory to deploy 
          server-dir: /public_html/  # The target directory on Hostinger 
